name: Сообщить о проблеме
description: Если вы столкнулись с проблемой -- расскажите, мы постараемся помочь
body:
  - type: textarea
    id: issue
    validations:
      required: true
    attributes:
      label: В чем проблема?
      description: >-
        Опишите проблему, с которой вы столкнулись. Расскажите что делаете, что происходит, какое поведенеи вы ожидаете.

        Постарайтесь описать проблему четко и лаконично.

  - type: markdown
    attributes:
      value: |
        ## Информация об установке

  - type: input
    id: integration_version
    validations:
      required: true
    attributes:
      label: При использовании какой версии интеграции возникает проблема?

  - type: input
    id: ha_version
    validations:
      required: true
    attributes:
      label: Какая версия Home Assistant используется?
      placeholder: core-
      description: >
        Можно посмотреть: Конфигурация -> Настройки -> О системе  - type: dropdown

  - type: dropdown
    id: installation_method
    validations:
      required: true
    attributes:
      label: Какой способ установки Home Assistant используется?
      description: >
         Можно посмотреть: Конфигурация -> Настройки -> О системе
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
        
  - type: checkboxes
    id: installation_actions completed
    attributes:
      label: самопроверка по созданию ключа
      description: (если интеграция до этого у вас работала -- при создании ключа вы все сделали правильно и можно не вспоминать как добавлялся ключ)
      options:      
        - label: при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
          required: true
        - label: тип ключа в кабинете разработчика был изменен на "погода для сайта"
          required: true
        - label: после изменения типа ключа прошло не менее 20 минут
          required: true
        - label: в кабинете разработчка я вижу что с запросы делаются именно с этим ключом
          required: true
          
  - type: markdown
    attributes:
      value: |
        # Детали

  - type: textarea
    id: log
    attributes:
      label: Есть что-нибудь полезное в логе?
      description: Cообщение об ошибке, trace итд.
      render: txt

  - type: textarea
    id: additional_info
    attributes:
      label: Дополнительная информация
      description: >
        Если нужно что-то добавить, напишите здесь.
