name: CI tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  tests:
    name: Run ${{ matrix.type }} tests for python ${{matrix.python}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9, 3.10]
        type: [unit, functional]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Prepare python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Run ${{ matrix.type }} tests
        run: python -m unittest discover -s tests/${{ matrix.type }} -v
